index.md: data/%.json scoring.R
	Rscript scoring.R

data/%.json:
	touch data/team1.json
	touch data/team2.json
	#touch data/team3.json
	touch data/team4.json
	touch data/team5.json
	touch data/team6.json
	touch data/team7.json
	touch data/team8.json
	#
	#cp ~/Sta523/HW/hw3/Team1/hw3/precinct.json data/team1.json
	#cp ~/Sta523/HW/hw3/Team2/HW3/precinct.json data/team2.json
	##cp ~/Sta523/HW/hw3/Team3/Homework3/precinct.json data/team3.json
	#cp ~/Sta523/HW/hw3/Team4/HW3/precinct.json data/team4.json
	#cp ~/Sta523/HW/hw3/Team5/HW3/precinct.json data/team5.json
	#cp ~/Sta523/HW/hw3/Team6/HW3/precinct.json data/team6.json
	##cp ~/Sta523/HW/hw3/Team7/Homework\ 3/precinct.json data/team7.json
	#cp ~/Sta523/HW/hw3/Team8/HW3/precinct.json data/team8.json
	#