---
layout: page
title: A brief tour of R<br/>package structure
reading: "<a href='http://cran.r-project.org/doc/manuals/r-release/R-exts.html'>Writing R Extensions</a><br/><a href='http://r-pkgs.had.co.nz'>R Packages</a>"
notes: ""
output: 
    ioslides_presentation:
        widescreen: true
        smaller: false
slides: true
---

```{r, echo=FALSE}
options(width = 110)
library(testthat)
context("Examples")
```


# R Packages

## Package Organization {.smaller}

Core requirements:

* `DESCRIPTION`: package metadata

* `R/`: home of your R code (.R files)

* `man/`: documentation

* `NAMESPACE`: specifies what objects are exposed

<br/>

Other helpful stuff:

* `vignettes/`: long-form documentation

* `tests/`: home of your unit tests

* `data/`: home of sample datasets

* `inst/`: anything else that should come along for the ride

* `src/`: compiled source code (e.g. C, C++ and/or Fortran)



## Initializing a package

The old way:

* Base R implementation `package.skeleton()`

The new way:

* Eddelbuettel's [pkgKitten](http://dirk.eddelbuettel.com/code/pkgkitten.html)

    * `kitten()` as a drop in replacement for `package.skeleton()`

<br/>

* Hadley's [devtools](https://github.com/hadley/devtools)

    * `create()` setups the basics, lots of other add ons and tie-ins.



## A tour of testthat {.flexbox .vcenter}

https://github.com/hadley/testthat



## Building and checking a package

The old way (via the shell):

* `R CMD build pkg` - construct a zipped file containing the package, source packages by default, but can compile and link source file if needed.

* `R CMD check pkg` - runs the *extensive* tests required by CRAN.

<br/>

The new way (via devtools):

* `build()` / `check()` - same stuff but inside of the R session.

## Back to testthat {.flexbox .vcenter}

https://github.com/hadley/testthat


## HW4 as a package


# Acknowledgments

## Acknowledgments

Above materials are derived in part from the following sources:

* [Writing R Extensions](http://cran.r-project.org/doc/manuals/r-release/R-exts.html)

* [Hadley's - R Packages](http://r-pkgs.had.co.nz/)

